site_name: My Docs

theme:
  name: material
  features:
    - navigation.tabs      # 开启顶部选项卡

nav:
  - 项目介绍: index.md
  - 项目环境搭建: 
      - 配置一览: 项目环境搭建/配置一览.md
      - 安装 Ubuntu 22.04 LTS: 项目环境搭建/安装ubuntu22.04操作系统.md
      - 安装 Verilator和gtkwave: 项目环境搭建/安装verilator和gtkwave.md
      - 安装库文件和编译工具: 项目环境搭建/安装库文件和编译工具.md  # 移到这里作为子项
      - 项目参考资料: 项目环境搭建/项目参考资料.md
  - 单周期处理器: 
        - 单周期测试框架介绍: 单周期处理器/单周期测试框架介绍.md
        - 使用内置处理器运行测试框架: 单周期处理器/使用内置处理器运行测试框架.md
        - 使用你的处理器运行测试框架: 单周期处理器/使用你的处理器运行测试框架.md
        - 单周期处理器启动RT-Thread: 单周期处理器/启动RT-Thread.md
  - 流水线处理器: 
        - 流水线测试框架介绍: 流水线处理器/流水线测试框架介绍.md
        - 使用内置处理器运行测试框架: 流水线处理器/使用内置处理器运行测试框架.md
        - 使用你的处理器运行测试框架: 流水线处理器/使用你的处理器运行测试框架.md
  - 处理器进阶设计: a.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences